package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Claim generated by hbm2java
 */
public class Claim implements java.io.Serializable {

	private Integer id;
	private ClaimType claimType;
	private SysUser sysUser;
	private String subject;
	private String description;
	private Boolean isFixed;
	private String userComment;
	private Set claimWorkflowSteps = new HashSet(0);
	private Set claimStatuses = new HashSet(0);
	private Set claimDocuments = new HashSet(0);
	private Set claimStatusSteps = new HashSet(0);
	private Set claimWorkflows = new HashSet(0);

	public Claim() {
	}

	public Claim(ClaimType claimType, SysUser sysUser) {
		this.claimType = claimType;
		this.sysUser = sysUser;
	}

	public Claim(ClaimType claimType, SysUser sysUser, String subject, String description, Boolean isFixed,
			String userComment, Set claimWorkflowSteps, Set claimStatuses, Set claimDocuments, Set claimStatusSteps,
			Set claimWorkflows) {
		this.claimType = claimType;
		this.sysUser = sysUser;
		this.subject = subject;
		this.description = description;
		this.isFixed = isFixed;
		this.userComment = userComment;
		this.claimWorkflowSteps = claimWorkflowSteps;
		this.claimStatuses = claimStatuses;
		this.claimDocuments = claimDocuments;
		this.claimStatusSteps = claimStatusSteps;
		this.claimWorkflows = claimWorkflows;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ClaimType getClaimType() {
		return this.claimType;
	}

	public void setClaimType(ClaimType claimType) {
		this.claimType = claimType;
	}

	public SysUser getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getIsFixed() {
		return this.isFixed;
	}

	public void setIsFixed(Boolean isFixed) {
		this.isFixed = isFixed;
	}

	public String getUserComment() {
		return this.userComment;
	}

	public void setUserComment(String userComment) {
		this.userComment = userComment;
	}

	public Set getClaimWorkflowSteps() {
		return this.claimWorkflowSteps;
	}

	public void setClaimWorkflowSteps(Set claimWorkflowSteps) {
		this.claimWorkflowSteps = claimWorkflowSteps;
	}

	public Set getClaimStatuses() {
		return this.claimStatuses;
	}

	public void setClaimStatuses(Set claimStatuses) {
		this.claimStatuses = claimStatuses;
	}

	public Set getClaimDocuments() {
		return this.claimDocuments;
	}

	public void setClaimDocuments(Set claimDocuments) {
		this.claimDocuments = claimDocuments;
	}

	public Set getClaimStatusSteps() {
		return this.claimStatusSteps;
	}

	public void setClaimStatusSteps(Set claimStatusSteps) {
		this.claimStatusSteps = claimStatusSteps;
	}

	public Set getClaimWorkflows() {
		return this.claimWorkflows;
	}

	public void setClaimWorkflows(Set claimWorkflows) {
		this.claimWorkflows = claimWorkflows;
	}

}
