package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

/**
 * ClaimDocument generated by hbm2java
 */
public class ClaimDocument implements java.io.Serializable {

	private String id;
	private Claim claim;
	private DocumentType documentType;
	private byte[] data;

	public ClaimDocument() {
	}

	public ClaimDocument(String id, Claim claim, DocumentType documentType) {
		this.id = id;
		this.claim = claim;
		this.documentType = documentType;
	}

	public ClaimDocument(String id, Claim claim, DocumentType documentType, byte[] data) {
		this.id = id;
		this.claim = claim;
		this.documentType = documentType;
		this.data = data;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Claim getClaim() {
		return this.claim;
	}

	public void setClaim(Claim claim) {
		this.claim = claim;
	}

	public DocumentType getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(DocumentType documentType) {
		this.documentType = documentType;
	}

	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

}
