package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

/**
 * ClaimWorkflow generated by hbm2java
 */
public class ClaimWorkflow implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -579914356534955099L;
	private Integer id;
	private Claim claim;
	private WorkflowDefinition workflowDefinition;

	public ClaimWorkflow() {
	}

	public ClaimWorkflow(Claim claim, WorkflowDefinition workflowDefinition) {
		this.claim = claim;
		this.workflowDefinition = workflowDefinition;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Claim getClaim() {
		return this.claim;
	}

	public void setClaim(Claim claim) {
		this.claim = claim;
	}

	public WorkflowDefinition getWorkflowDefinition() {
		return this.workflowDefinition;
	}

	public void setWorkflowDefinition(WorkflowDefinition workflowDefinition) {
		this.workflowDefinition = workflowDefinition;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClaimWorkflow other = (ClaimWorkflow) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ClaimWorkflow [id=" + id + "]";
	}

}
