package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

/**
 * ClaimWorkflow generated by hbm2java
 */
public class ClaimWorkflow implements java.io.Serializable {

	private Integer id;
	private Claim claim;
	private WorkflowDefinition workflowDefinition;

	public ClaimWorkflow() {
	}

	public ClaimWorkflow(Claim claim, WorkflowDefinition workflowDefinition) {
		this.claim = claim;
		this.workflowDefinition = workflowDefinition;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Claim getClaim() {
		return this.claim;
	}

	public void setClaim(Claim claim) {
		this.claim = claim;
	}

	public WorkflowDefinition getWorkflowDefinition() {
		return this.workflowDefinition;
	}

	public void setWorkflowDefinition(WorkflowDefinition workflowDefinition) {
		this.workflowDefinition = workflowDefinition;
	}

}
