package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

/**
 * ClaimWorkflowStep generated by hbm2java
 */
public class ClaimWorkflowStep implements java.io.Serializable {

	private Integer id;
	private Claim claim;
	private SysUser sysUser;
	private WorkflowDefinition workflowDefinition;
	private String userComment;

	public ClaimWorkflowStep() {
	}

	public ClaimWorkflowStep(Claim claim, SysUser sysUser, WorkflowDefinition workflowDefinition) {
		this.claim = claim;
		this.sysUser = sysUser;
		this.workflowDefinition = workflowDefinition;
	}

	public ClaimWorkflowStep(Claim claim, SysUser sysUser, WorkflowDefinition workflowDefinition, String userComment) {
		this.claim = claim;
		this.sysUser = sysUser;
		this.workflowDefinition = workflowDefinition;
		this.userComment = userComment;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Claim getClaim() {
		return this.claim;
	}

	public void setClaim(Claim claim) {
		this.claim = claim;
	}

	public SysUser getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

	public WorkflowDefinition getWorkflowDefinition() {
		return this.workflowDefinition;
	}

	public void setWorkflowDefinition(WorkflowDefinition workflowDefinition) {
		this.workflowDefinition = workflowDefinition;
	}

	public String getUserComment() {
		return this.userComment;
	}

	public void setUserComment(String userComment) {
		this.userComment = userComment;
	}

}
