package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

/**
 * ClaimStatus generated by hbm2java
 */
public class ClaimStatus implements java.io.Serializable {

	private Integer id;
	private Claim claim;
	private Organization organization;
	private Status status;

	public ClaimStatus() {
	}

	public ClaimStatus(Claim claim, Organization organization, Status status) {
		this.claim = claim;
		this.organization = organization;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Claim getClaim() {
		return this.claim;
	}

	public void setClaim(Claim claim) {
		this.claim = claim;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

}
