package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentType generated by hbm2java
 */
public class DocumentType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2555501497957064034L;
	private Short id;
	private String arabicName;
	private String englishName;
	private String description;
	private String code;
	private Set<ClaimDocument> claimDocuments = new HashSet<ClaimDocument>(0);

	public DocumentType() {
	}

	public DocumentType(String arabicName, String englishName) {
		this.arabicName = arabicName;
		this.englishName = englishName;
	}

	public DocumentType(String arabicName, String englishName, String description, String code, Set<ClaimDocument>  claimDocuments) {
		this.arabicName = arabicName;
		this.englishName = englishName;
		this.description = description;
		this.code = code;
		this.claimDocuments = claimDocuments;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public String getArabicName() {
		return this.arabicName;
	}

	public void setArabicName(String arabicName) {
		this.arabicName = arabicName;
	}

	public String getEnglishName() {
		return this.englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set<ClaimDocument>  getClaimDocuments() {
		return this.claimDocuments;
	}

	public void setClaimDocuments(Set<ClaimDocument>  claimDocuments) {
		this.claimDocuments = claimDocuments;
	}

}
