package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2360395520550876885L;
	private Integer id;
	private Organization organization;
	private String arabicName;
	private String englishName;
	private String code;
	private Set<ClaimStatus> claimStatuses = new HashSet<ClaimStatus>(0);
	private Set<SysUserOrganization> sysUserOrganizations = new HashSet<SysUserOrganization>(0);
	private Set<ClaimStatusStep> claimStatusSteps = new HashSet<ClaimStatusStep>(0);
	private Set<Organization> organizations = new HashSet<Organization>(0);

	public Organization() {
	}

	public Organization(Organization organization, String arabicName, String englishName, String code) {
		this.organization = organization;
		this.arabicName = arabicName;
		this.englishName = englishName;
		this.code = code;
	}



	public Organization(Integer id, Organization organization, String arabicName, String englishName, String code,
			Set<ClaimStatus> claimStatuses, Set<SysUserOrganization> sysUserOrganizations,
			Set<ClaimStatusStep> claimStatusSteps, Set<Organization> organizations) {
		super();
		this.id = id;
		this.organization = organization;
		this.arabicName = arabicName;
		this.englishName = englishName;
		this.code = code;
		this.claimStatuses = claimStatuses;
		this.sysUserOrganizations = sysUserOrganizations;
		this.claimStatusSteps = claimStatusSteps;
		this.organizations = organizations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public String getArabicName() {
		return this.arabicName;
	}

	public void setArabicName(String arabicName) {
		this.arabicName = arabicName;
	}

	public String getEnglishName() {
		return this.englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set<ClaimStatus> getClaimStatuses() {
		return claimStatuses;
	}

	public void setClaimStatuses(Set<ClaimStatus> claimStatuses) {
		this.claimStatuses = claimStatuses;
	}

	public Set<SysUserOrganization> getSysUserOrganizations() {
		return sysUserOrganizations;
	}

	public void setSysUserOrganizations(Set<SysUserOrganization> sysUserOrganizations) {
		this.sysUserOrganizations = sysUserOrganizations;
	}

	public Set<ClaimStatusStep> getClaimStatusSteps() {
		return claimStatusSteps;
	}

	public void setClaimStatusSteps(Set<ClaimStatusStep> claimStatusSteps) {
		this.claimStatusSteps = claimStatusSteps;
	}

	public Set<Organization> getOrganizations() {
		return organizations;
	}

	public void setOrganizations(Set<Organization> organizations) {
		this.organizations = organizations;
	}

	
}
