package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization implements java.io.Serializable {

	private Integer id;
	private Organization organization;
	private String arabicName;
	private String englishName;
	private String code;
	private Set claimStatuses = new HashSet(0);
	private Set sysUserOrganizations = new HashSet(0);
	private Set claimStatusSteps = new HashSet(0);
	private Set organizations = new HashSet(0);

	public Organization() {
	}

	public Organization(Organization organization, String arabicName, String englishName, String code) {
		this.organization = organization;
		this.arabicName = arabicName;
		this.englishName = englishName;
		this.code = code;
	}

	public Organization(Organization organization, String arabicName, String englishName, String code,
			Set claimStatuses, Set sysUserOrganizations, Set claimStatusSteps, Set organizations) {
		this.organization = organization;
		this.arabicName = arabicName;
		this.englishName = englishName;
		this.code = code;
		this.claimStatuses = claimStatuses;
		this.sysUserOrganizations = sysUserOrganizations;
		this.claimStatusSteps = claimStatusSteps;
		this.organizations = organizations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public String getArabicName() {
		return this.arabicName;
	}

	public void setArabicName(String arabicName) {
		this.arabicName = arabicName;
	}

	public String getEnglishName() {
		return this.englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set getClaimStatuses() {
		return this.claimStatuses;
	}

	public void setClaimStatuses(Set claimStatuses) {
		this.claimStatuses = claimStatuses;
	}

	public Set getSysUserOrganizations() {
		return this.sysUserOrganizations;
	}

	public void setSysUserOrganizations(Set sysUserOrganizations) {
		this.sysUserOrganizations = sysUserOrganizations;
	}

	public Set getClaimStatusSteps() {
		return this.claimStatusSteps;
	}

	public void setClaimStatusSteps(Set claimStatusSteps) {
		this.claimStatusSteps = claimStatusSteps;
	}

	public Set getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set organizations) {
		this.organizations = organizations;
	}

}
