package com.claim.model.entity;
// Generated 10/03/2018 11:10:21 ? by Hibernate Tools 5.1.0.Beta1

/**
 * RolePermission generated by hbm2java
 */
public class RolePermission implements java.io.Serializable {

	private Integer id;
	private SysPermission sysPermission;
	private SysRole sysRole;

	public RolePermission() {
	}

	public RolePermission(SysPermission sysPermission, SysRole sysRole) {
		this.sysPermission = sysPermission;
		this.sysRole = sysRole;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SysPermission getSysPermission() {
		return this.sysPermission;
	}

	public void setSysPermission(SysPermission sysPermission) {
		this.sysPermission = sysPermission;
	}

	public SysRole getSysRole() {
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

}
