package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

/**
 * SysUserOrganization generated by hbm2java
 */
public class SysUserOrganization implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6216530640829210208L;
	private Integer id;
	private Organization organization;
	private SysUser sysUser;

	public SysUserOrganization() {
	}

	public SysUserOrganization(Organization organization, SysUser sysUser) {
		this.organization = organization;
		this.sysUser = sysUser;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public SysUser getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

}
