package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * SysUser generated by hbm2java
 */
public class SysUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -248922526097461101L;
	private Integer id;
	private String userName;
	private String password;
	private String name;
	private String surname;
	private String fatherName;
	private String motherName;
	private Set<ClaimStatusStep> claimWorkflowSteps = new HashSet<ClaimStatusStep>(0);
	private Set<ClaimStatusStep> claimStatusSteps = new HashSet<ClaimStatusStep>(0);
	private Set<Claim> claims = new HashSet<Claim>(0);
	private Set<SysUserOrganization> sysUserOrganizations = new HashSet<SysUserOrganization>(0);
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);

	public SysUser() {
	}
	public SysUser(Integer id, String userName, String password, String name, String surname, String fatherName,
			String motherName, Set<ClaimStatusStep> claimWorkflowSteps, Set<ClaimStatusStep> claimStatusSteps,
			Set<Claim> claims, Set<SysUserOrganization> sysUserOrganizations, Set<UserRole> userRoles) {
		super();
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.fatherName = fatherName;
		this.motherName = motherName;
		this.claimWorkflowSteps = claimWorkflowSteps;
		this.claimStatusSteps = claimStatusSteps;
		this.claims = claims;
		this.sysUserOrganizations = sysUserOrganizations;
		this.userRoles = userRoles;
	}



	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}



	public Set<ClaimStatusStep> getClaimWorkflowSteps() {
		return claimWorkflowSteps;
	}



	public void setClaimWorkflowSteps(Set<ClaimStatusStep> claimWorkflowSteps) {
		this.claimWorkflowSteps = claimWorkflowSteps;
	}



	public Set<ClaimStatusStep> getClaimStatusSteps() {
		return claimStatusSteps;
	}



	public void setClaimStatusSteps(Set<ClaimStatusStep> claimStatusSteps) {
		this.claimStatusSteps = claimStatusSteps;
	}



	public Set<Claim> getClaims() {
		return claims;
	}



	public void setClaims(Set<Claim> claims) {
		this.claims = claims;
	}



	public Set<SysUserOrganization> getSysUserOrganizations() {
		return sysUserOrganizations;
	}



	public void setSysUserOrganizations(Set<SysUserOrganization> sysUserOrganizations) {
		this.sysUserOrganizations = sysUserOrganizations;
	}



	public Set<UserRole> getUserRoles() {
		return userRoles;
	}



	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	
	@Override
	public String toString() {
		return "SysUser [id=" + id + ", userName=" + userName + ", password=" + password + ", name=" + name
				+ ", surname=" + surname + ", fatherName=" + fatherName + ", motherName=" + motherName + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fatherName == null) ? 0 : fatherName.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((motherName == null) ? 0 : motherName.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((password == null) ? 0 : password.hashCode());
		result = prime * result + ((surname == null) ? 0 : surname.hashCode());
		result = prime * result + ((userName == null) ? 0 : userName.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SysUser other = (SysUser) obj;
		if (fatherName == null) {
			if (other.fatherName != null)
				return false;
		} else if (!fatherName.equals(other.fatherName))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (motherName == null) {
			if (other.motherName != null)
				return false;
		} else if (!motherName.equals(other.motherName))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (password == null) {
			if (other.password != null)
				return false;
		} else if (!password.equals(other.password))
			return false;
		if (surname == null) {
			if (other.surname != null)
				return false;
		} else if (!surname.equals(other.surname))
			return false;
		if (userName == null) {
			if (other.userName != null)
				return false;
		} else if (!userName.equals(other.userName))
			return false;
		return true;
	}



}
