package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * WorkflowDefinition generated by hbm2java
 */
public class WorkflowDefinition implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4867397164668591743L;
	private Integer id;
	private Step step;
	private Workflow workflow;
	private WorkflowDefinition workflowDefinitionByNext;
	private WorkflowDefinition workflowDefinitionByPrevious;
	private Boolean initialStep;
	private Boolean finalStep;
	private Set<ClaimStatusStep> claimWorkflowSteps = new HashSet<ClaimStatusStep>(0);
	private Set<WorkflowDefinition> workflowDefinitionsForNext = new HashSet<WorkflowDefinition>(0);
	private Set<WorkflowDefinition> workflowDefinitionsForPrevious = new HashSet<WorkflowDefinition>(0);
	private Set<ClaimWorkflow> claimWorkflows = new HashSet<ClaimWorkflow>(0);

	public WorkflowDefinition() {
	}



	public WorkflowDefinition(Integer id, Step step, Workflow workflow, WorkflowDefinition workflowDefinitionByNext,
			WorkflowDefinition workflowDefinitionByPrevious, Boolean initialStep, Boolean finalStep,
			Set<ClaimStatusStep> claimWorkflowSteps, Set<WorkflowDefinition> workflowDefinitionsForNext,
			Set<WorkflowDefinition> workflowDefinitionsForPrevious, Set<ClaimWorkflow> claimWorkflows) {
		super();
		this.id = id;
		this.step = step;
		this.workflow = workflow;
		this.workflowDefinitionByNext = workflowDefinitionByNext;
		this.workflowDefinitionByPrevious = workflowDefinitionByPrevious;
		this.initialStep = initialStep;
		this.finalStep = finalStep;
		this.claimWorkflowSteps = claimWorkflowSteps;
		this.workflowDefinitionsForNext = workflowDefinitionsForNext;
		this.workflowDefinitionsForPrevious = workflowDefinitionsForPrevious;
		this.claimWorkflows = claimWorkflows;
	}



	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Step getStep() {
		return this.step;
	}

	public void setStep(Step step) {
		this.step = step;
	}

	public Workflow getWorkflow() {
		return this.workflow;
	}

	public void setWorkflow(Workflow workflow) {
		this.workflow = workflow;
	}

	public WorkflowDefinition getWorkflowDefinitionByNext() {
		return this.workflowDefinitionByNext;
	}

	public void setWorkflowDefinitionByNext(WorkflowDefinition workflowDefinitionByNext) {
		this.workflowDefinitionByNext = workflowDefinitionByNext;
	}

	public WorkflowDefinition getWorkflowDefinitionByPrevious() {
		return this.workflowDefinitionByPrevious;
	}

	public void setWorkflowDefinitionByPrevious(WorkflowDefinition workflowDefinitionByPrevious) {
		this.workflowDefinitionByPrevious = workflowDefinitionByPrevious;
	}

	public Boolean getInitialStep() {
		return this.initialStep;
	}

	public void setInitialStep(Boolean initialStep) {
		this.initialStep = initialStep;
	}

	public Boolean getFinalStep() {
		return this.finalStep;
	}

	public void setFinalStep(Boolean finalStep) {
		this.finalStep = finalStep;
	}



	public Set<ClaimStatusStep> getClaimWorkflowSteps() {
		return claimWorkflowSteps;
	}



	public void setClaimWorkflowSteps(Set<ClaimStatusStep> claimWorkflowSteps) {
		this.claimWorkflowSteps = claimWorkflowSteps;
	}



	public Set<WorkflowDefinition> getWorkflowDefinitionsForNext() {
		return workflowDefinitionsForNext;
	}



	public void setWorkflowDefinitionsForNext(Set<WorkflowDefinition> workflowDefinitionsForNext) {
		this.workflowDefinitionsForNext = workflowDefinitionsForNext;
	}



	public Set<WorkflowDefinition> getWorkflowDefinitionsForPrevious() {
		return workflowDefinitionsForPrevious;
	}



	public void setWorkflowDefinitionsForPrevious(Set<WorkflowDefinition> workflowDefinitionsForPrevious) {
		this.workflowDefinitionsForPrevious = workflowDefinitionsForPrevious;
	}



	public Set<ClaimWorkflow> getClaimWorkflows() {
		return claimWorkflows;
	}



	public void setClaimWorkflows(Set<ClaimWorkflow> claimWorkflows) {
		this.claimWorkflows = claimWorkflows;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((finalStep == null) ? 0 : finalStep.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((initialStep == null) ? 0 : initialStep.hashCode());
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		WorkflowDefinition other = (WorkflowDefinition) obj;
		if (finalStep == null) {
			if (other.finalStep != null)
				return false;
		} else if (!finalStep.equals(other.finalStep))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (initialStep == null) {
			if (other.initialStep != null)
				return false;
		} else if (!initialStep.equals(other.initialStep))
			return false;
		return true;
	}



	@Override
	public String toString() {
		return "WorkflowDefinition [id=" + id + ", initialStep=" + initialStep + ", finalStep=" + finalStep + "]";
	}

	

}
