package com.claim.model.entity;
// Generated 03/04/2018 11:59:14 ? by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * WorkflowDefinition generated by hbm2java
 */
public class WorkflowDefinition implements java.io.Serializable {

	private Integer id;
	private Step step;
	private Workflow workflow;
	private WorkflowDefinition workflowDefinitionByNext;
	private WorkflowDefinition workflowDefinitionByPrevious;
	private Boolean initialStep;
	private Boolean finalStep;
	private Set claimWorkflowSteps = new HashSet(0);
	private Set workflowDefinitionsForNext = new HashSet(0);
	private Set workflowDefinitionsForPrevious = new HashSet(0);
	private Set claimWorkflows = new HashSet(0);

	public WorkflowDefinition() {
	}

	public WorkflowDefinition(Step step, Workflow workflow, WorkflowDefinition workflowDefinitionByNext,
			WorkflowDefinition workflowDefinitionByPrevious, Boolean initialStep, Boolean finalStep,
			Set claimWorkflowSteps, Set workflowDefinitionsForNext, Set workflowDefinitionsForPrevious,
			Set claimWorkflows) {
		this.step = step;
		this.workflow = workflow;
		this.workflowDefinitionByNext = workflowDefinitionByNext;
		this.workflowDefinitionByPrevious = workflowDefinitionByPrevious;
		this.initialStep = initialStep;
		this.finalStep = finalStep;
		this.claimWorkflowSteps = claimWorkflowSteps;
		this.workflowDefinitionsForNext = workflowDefinitionsForNext;
		this.workflowDefinitionsForPrevious = workflowDefinitionsForPrevious;
		this.claimWorkflows = claimWorkflows;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Step getStep() {
		return this.step;
	}

	public void setStep(Step step) {
		this.step = step;
	}

	public Workflow getWorkflow() {
		return this.workflow;
	}

	public void setWorkflow(Workflow workflow) {
		this.workflow = workflow;
	}

	public WorkflowDefinition getWorkflowDefinitionByNext() {
		return this.workflowDefinitionByNext;
	}

	public void setWorkflowDefinitionByNext(WorkflowDefinition workflowDefinitionByNext) {
		this.workflowDefinitionByNext = workflowDefinitionByNext;
	}

	public WorkflowDefinition getWorkflowDefinitionByPrevious() {
		return this.workflowDefinitionByPrevious;
	}

	public void setWorkflowDefinitionByPrevious(WorkflowDefinition workflowDefinitionByPrevious) {
		this.workflowDefinitionByPrevious = workflowDefinitionByPrevious;
	}

	public Boolean getInitialStep() {
		return this.initialStep;
	}

	public void setInitialStep(Boolean initialStep) {
		this.initialStep = initialStep;
	}

	public Boolean getFinalStep() {
		return this.finalStep;
	}

	public void setFinalStep(Boolean finalStep) {
		this.finalStep = finalStep;
	}

	public Set getClaimWorkflowSteps() {
		return this.claimWorkflowSteps;
	}

	public void setClaimWorkflowSteps(Set claimWorkflowSteps) {
		this.claimWorkflowSteps = claimWorkflowSteps;
	}

	public Set getWorkflowDefinitionsForNext() {
		return this.workflowDefinitionsForNext;
	}

	public void setWorkflowDefinitionsForNext(Set workflowDefinitionsForNext) {
		this.workflowDefinitionsForNext = workflowDefinitionsForNext;
	}

	public Set getWorkflowDefinitionsForPrevious() {
		return this.workflowDefinitionsForPrevious;
	}

	public void setWorkflowDefinitionsForPrevious(Set workflowDefinitionsForPrevious) {
		this.workflowDefinitionsForPrevious = workflowDefinitionsForPrevious;
	}

	public Set getClaimWorkflows() {
		return this.claimWorkflows;
	}

	public void setClaimWorkflows(Set claimWorkflows) {
		this.claimWorkflows = claimWorkflows;
	}

}
